version: '3.9'

services:
  backend-client:
    image: 'docker-spring-boot-postgres:latest'
    build: ./

    container_name: 'messenger'
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=postgresql://db:3306/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDT_AUTO=update

  db:
    image: 'postgres:13-alpine'
    container_name: db
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=postgres'
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: unless-stopped